name: get-last-run.yml
on: [workflow_dispatch, push]

jobs:
  last-run:
    runs-on: ubuntu-latest
    steps:
      - name: Get previous workflow status
        uses: Mercymeilya/last-workflow-status@v0.3.3
        id: last_status
        with:
          github_token: ${{ secrets.demoToken }}
