name: Use pre-commit

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - run: |
          echo "pre-commit" > requirements.txt
    
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip

      - name: Validations
        run: |
          echo '${{ toJson(runner) }}'
          python3 --version
          pip --version

      - name: Install & Run pre-commit
        run: |
          pip install pre-commit
          pre-commit --version
          pre-commit install
          pre-commit run --all-files