name: Use pre-commit

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python3 --version

      - name: Echo runner context
        run: echo '${{ toJson(runner) }}'
      
      - name: Check pip
        run: echo pip --version

      - name: Install & Run pre-commit
        run: |
          pip install pre-commit
          echo pre-commit --version

      # - name: Cache dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: