name: Use pre-commit

on:
  workflow_dispatch:
    inputs:
      name:
        description: "name of the person"
        default: "Noman"
        type: string
        required: false
  pull_request:
    branches: 
      - main
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Log context obj
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "Input var name: ${{ github.event.inputs.name }}"
          echo "GITHUB_CONTEXT: $GITHUB_CONTEXT"

  job2:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.step1value }}
      output2: ${{ steps.step2.outputs.step2value }}
    steps:
      - name: Create 1st output var
        id: step1
        run: echo "step1value=hello" >> $GITHUB_OUTPUT
      - name: Create 2nd output var
        id: step2
        run: echo "step2value=world" >> $GITHUB_OUTPUT

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo ${{ needs.job2.outputs.output1 }} ${{ needs.job2.outputs.output2}}

  job4:
    runs-on: ubuntu-latest
