name: test-order-of-code-run
on: [workflow_dispatch, push]

jobs:
  test_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    name: Build on ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "I am farmer"
          echo -e "${{ toJson(runner) }}"

