name: ci
on:
  push:
    branches:
    - '**'
    paths-ignore:
    - .github/workflows/**
    - '**.md'
  workflow_dispatch:
jobs:
  ci:
    uses: actions/cache@v3
    with:
      branch: "develop"
    secrets: inherit
