name: ci
'on':
  push:
    branches:
      - '**'
    paths-ignore:
      - .github/workflows/**
      - '**.md'
  workflow_dispatch: null
jobs:
  ci:
    uses: actions/cache@v3
    with:
      branch: develop
      code-qual: true
    secrets: inherit
