


name: Check last build on main
on: workflow_dispatch
jobs:
  getLastBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check last build
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=main&status=completed&per_page=1")

          conclusion=$(echo "$response" | jq -r '.workflow_runs[0].conclusion')
          url=$(echo "$response" | jq -r '.workflow_runs[0].html_url')

          if [ "$conclusion" != "success" ]; then
            echo "Last build failed or was not successful: $url"
            exit 1
          else
            echo "Last build on main was successful: $url"
          fi
