name: Check last build on main
on: workflow_dispatch
jobs:
  get_last_build:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: get repo to check fields
        run: |
          response=$(curl -L -s "https://github.com/ethawn234/gha-data")
          echo $response
      - name: Check last build
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.demoToken }}" \
            -w "%{}"
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=main&status=completed&per_page=1")

          echo -e "\nRESPONSE: $response \nREPOSITORY: ${{github.repository}}"

          conclusion=$(echo "$response" | jq -r '.workflow_runs[0].conclusion')
          url=$(echo "$response" | jq -r '.workflow_runs[0].html_url') 

          if [ "$conclusion" != "success" ]; then
            echo "Last build failed or was not successful: $url"
            exit 1
          else
            echo "Last build on main was successful: $url"
          fi
  validate_get_last_build_wf:
    needs: get_last_build
    if: always()
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find matching workflow
        uses: SamhammerAG/last-successful-build-action@v4 # This action searches for the last successful workflow-run for the given workflow-name and branch. The sha of the workflow-commit is set as output-parameter. If no matching workflow exists, the sha of the current run is emitted.
        with:
          token: "${{ secrets.demoToken }}"
          branch: "main"
          workflow: "Check last build on main"
